# Generated by Django 2.2 on 2025-03-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=120)),
                ('econtact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
